### ISSUE TITLE
ypeError: unsupported operand type(s) for %: ‘int’ and ‘NoneType’

### ISSUE THREAD

**Issue by ghoshaw** [taki0112/Tensorflow-Cookbook#2]
hi, first thanks for your brilliant work.
     Using the conv in ops.py could lead to error "typeError: unsupported operand type(s) for %: ‘int’ and ‘NoneType’", this error is  caused by "if h % stride == 0:" and I figured maybe I can set the h in the function, but it can not be used in training with changed size. Is any idea how to modify  it?

**Comment by taki0112** [comment]
Maybe the height, width of the input shape is a none type.
Is there a reason why you must use a None type?
