### ISSUE TITLE
How about TF2?

### ISSUE THREAD

**Issue by Honlan** [taki0112/Tensorflow-Cookbook#3]
Hi, taki, thanks a lot for your awesome cookbook.

Have you ever considered publishing another version of this cookbook by TensorFlow2.0?

**Comment by taki0112** [comment]
I'm changing the code to 2.0 now.
I'll update it as soon as it's finished.

**Comment by Honlan** [comment]
> I'm changing the code to 2.0 now.
> I'll update it as soon as it's finished.

Awesome! Thanks a lot~

**Comment by taki0112** [comment]
@Honlan 
https://github.com/taki0112/Tensorflow2-Cookbook

will be soon.
